uploads = []
outputs = []

[[generated]]
id = "bb6f8aNvCNc02FyhWFaEz"
uri = "file://artifacts/mockup-sandbox/public/images/industrial-bg.png"
type = "image"
title = "dark industrial grid texture"

[[generated]]
id = "jlYt01ZdaIU0zi_A5MWGX"
uri = "file://artifacts/mockup-sandbox/public/images/cyberpunk-anime-bg.png"
type = "image"
title = "Cyberpunk anime character background"
