// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-layouts/AsymmetricGrid.tsx": () => import("../components/mockups/login-layouts/AsymmetricGrid.tsx"),
  "./components/mockups/login-layouts/CenteredStack.tsx": () => import("../components/mockups/login-layouts/CenteredStack.tsx"),
  "./components/mockups/login-layouts/DashboardBar.tsx": () => import("../components/mockups/login-layouts/DashboardBar.tsx"),
  "./components/mockups/recent-winner/Current.tsx": () => import("../components/mockups/recent-winner/Current.tsx"),
  "./components/mockups/recent-winner/Refined.tsx": () => import("../components/mockups/recent-winner/Refined.tsx"),
  "./components/mockups/session-ordering/CommandCenter.tsx": () => import("../components/mockups/session-ordering/CommandCenter.tsx"),
  "./components/mockups/session-ordering/CompetitiveLounge.tsx": () => import("../components/mockups/session-ordering/CompetitiveLounge.tsx"),
  "./components/mockups/session-ordering/StoreFirst.tsx": () => import("../components/mockups/session-ordering/StoreFirst.tsx"),
  "./components/mockups/session-bar-balance/CompactDock.tsx": () => import("../components/mockups/session-bar-balance/CompactDock.tsx"),
  "./components/mockups/session-bar-balance/Current.tsx": () => import("../components/mockups/session-bar-balance/Current.tsx"),
  "./components/mockups/session-bar-balance/PlayerCard.tsx": () => import("../components/mockups/session-bar-balance/PlayerCard.tsx"),
  "./components/mockups/session-bar-balance/TimeFirst.tsx": () => import("../components/mockups/session-bar-balance/TimeFirst.tsx"),
  "./components/mockups/session-view/LayoutA.tsx": () => import("../components/mockups/session-view/LayoutA.tsx"),
  "./components/mockups/session-view/LayoutB.tsx": () => import("../components/mockups/session-view/LayoutB.tsx"),
  "./components/mockups/session-view/LayoutC.tsx": () => import("../components/mockups/session-view/LayoutC.tsx"),
  "./components/mockups/session-view/SessionPanel.tsx": () => import("../components/mockups/session-view/SessionPanel.tsx"),
  "./components/mockups/session-view/SessionWithPoints.tsx": () => import("../components/mockups/session-view/SessionWithPoints.tsx")
};
