// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-layouts/AsymmetricGrid.tsx": () => import("../components/mockups/login-layouts/AsymmetricGrid.tsx"),
  "./components/mockups/login-layouts/CenteredStack.tsx": () => import("../components/mockups/login-layouts/CenteredStack.tsx"),
  "./components/mockups/login-layouts/DashboardBar.tsx": () => import("../components/mockups/login-layouts/DashboardBar.tsx")
};
