// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-layouts/AsymmetricGrid.tsx": () => import("../components/mockups/login-layouts/AsymmetricGrid.tsx"),
  "./components/mockups/login-layouts/CenteredStack.tsx": () => import("../components/mockups/login-layouts/CenteredStack.tsx"),
  "./components/mockups/login-layouts/DashboardBar.tsx": () => import("../components/mockups/login-layouts/DashboardBar.tsx"),
  "./components/mockups/session-view/LayoutA.tsx": () => import("../components/mockups/session-view/LayoutA.tsx"),
  "./components/mockups/session-view/LayoutB.tsx": () => import("../components/mockups/session-view/LayoutB.tsx"),
  "./components/mockups/session-view/LayoutC.tsx": () => import("../components/mockups/session-view/LayoutC.tsx"),
  "./components/mockups/session-view/SessionPanel.tsx": () => import("../components/mockups/session-view/SessionPanel.tsx"),
  "./components/mockups/session-view/SessionWithPoints.tsx": () => import("../components/mockups/session-view/SessionWithPoints.tsx")
};
